name: Test

on:
  push:
    branches: [ main ]
    paths:
    - 'src/**'
    - 'scripts/**'
    - 'poly/**'
    - '.github/workflows/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js v16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x

    - name: Pack base asar
      run: |
        npm i -g asar
        bash scripts/injectPolyfills.sh
        sed -i -e "s/nightly/nightly-$(git rev-parse HEAD | cut -c 1-7)/" src/index.js
        node scripts/strip.js
        npx asar pack src app.asar
